site:
  title: OpenCPN Basic
  url: https://Rasbats.github.io/opencpn-inland-ecdis/

content:
  branches:
    - main
    
  sources:
  - url: ./
    branches: HEAD

  - url: ./
    branches: HEAD
    start_paths:
     - content/en
     
  - url: ./
    branches: HEAD
    start_paths:
     - content/fr
      
ui:
  bundle:
    url: ./ui-bundle.zip
    snapshot: true
    
output:  
  dir: ./docs
  clean: true
  
#runtime:
#  pull: true
#  cache_dir: ./cache
